"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['decksDe.py','parserIMGS.py','pparser.py','vynilFuture.py']
OPTIONS = {'includes':['requests','openpyxl','beautifulsoup4','lxml']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
